{{- if .Values.global.localpathEnable }}
{{- if .Values.defaultSettings.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultSettings.registrySecret }}
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "local-path-provisioner.secret" . }}
{{- end }}
{{- end -}}